AWSTemplateFormatVersion: '2010-09-09'
Description: Primary Region Network (VPC + 2 Public Subnets + IGW + Routes) for DR Reference

Parameters:
  StackPrefix:
    Type: String
    Default: dr-primary
    Description: Prefix used for names/exports (keep unique per environment)
  VpcCidr:
    Type: String
    Default: 10.10.0.0/16
  PublicSubnet1Cidr:
    Type: String
    Default: 10.10.1.0/24
  PublicSubnet2Cidr:
    Type: String
    Default: 10.10.2.0/24

Mappings:
  RegionMap:
    ca-central-1:
      AZ1: a
      AZ2: b

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - { Key: Name, Value: !Sub '${StackPrefix}-vpc' }

  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags: [ { Key: Name, Value: !Sub '${StackPrefix}-igw' } ]

  AttachIgw:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref IGW

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Sub 'ca-central-1${RegionMap.ca-central-1.AZ1}'
      CidrBlock: !Ref PublicSubnet1Cidr
      MapPublicIpOnLaunch: true
      Tags: [ { Key: Name, Value: !Sub '${StackPrefix}-public-a' } ]

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Sub 'ca-central-1${RegionMap.ca-central-1.AZ2}'
      CidrBlock: !Ref PublicSubnet2Cidr
      MapPublicIpOnLaunch: true
      Tags: [ { Key: Name, Value: !Sub '${StackPrefix}-public-b' } ]

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags: [ { Key: Name, Value: !Sub '${StackPrefix}-public-rt' } ]

  DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW

  AssocPub1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  AssocPub2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

Outputs:
  VpcId:
    Description: Primary VPC Id
    Value: !Ref VPC
    Export:
      Name: !Sub '${StackPrefix}-VpcId'

  PublicSubnet1Id:
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub '${StackPrefix}-PublicSubnet1Id'

  PublicSubnet2Id:
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub '${StackPrefix}-PublicSubnet2Id'

  PublicSubnetIdsCsv:
    Description: Comma-separated public subnet IDs
    Value: !Join [ ",", [ !Ref PublicSubnet1, !Ref PublicSubnet2 ] ]
    Export:
      Name: !Sub '${StackPrefix}-PublicSubnetIdsCsv'
